# Generated by Django 6.0.4 on 2026-08-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='seller',
            field=models.ForeignKey(db_column='seller_id', on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='users.user'),
        ),
    ]
