# Generated by Django 6.0.4 on 2026-08-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_auctionitem_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionitem',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='auctionitem',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
