# Generated by Django 6.0.4 on 2026-08-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionitem_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
