# Generated by Django 6.0.4 on 2026-08-31 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionitem_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='is_active',
        ),
    ]
